{% set name = "riccati" %}
{% set version = "1.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/riccati-{{ version }}.tar.gz
  sha256: b409f17bc6cf5989b560d77a0baf433ac973cd16a5a111f07360b6627d5a89c0 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - setuptools-scm
    - pytest-runner
    - pip
    - versioneer
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - riccati
    - numpy
    - scipy
    - mpmath
  commands:
    - pip check
    - python -m pytest riccati/tests
  requires:
    - pip
    - numpy
    - scipy
    - mpmath
    - pytest
    - python {{ python_min }}
  source_files:
    - riccati/tests
    - riccati/tests/test_riccati.py

about:
  home: https://github.com/fruzsinaagocs/riccati
  summary: adaptive Riccati defect correction solver
  description: |
    riccati is a Python package for solving second order, linear, homogeneous
    ordinary differential equations with solutions that may become highly
    oscillatory over the solution interval. It implements the adaptive Riccati
    defect correction method described in https://arxiv.org/abs/2212.06924.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://riccati.readthedocs.io/
  dev_url: https://github.com/fruzsinaagocs/riccati

extra:
  recipe-maintainers:
    - fruzsinaagocs
